// import autogenerated files
const helloPb = require("./proto/hello_pb")
const axios = require("axios")

// Usage of the generated code
const helloRequest = new helloPb.HelloRequest()
helloRequest.setFirstName("tino")
helloRequest.setLastName("tham")

const metadata = new helloPb.Metadata()
metadata.setFNameLetterCount(helloRequest.getFirstName().length)
metadata.setLNameLetterCount(helloRequest.getLastName().length)
helloRequest.setMetadata(metadata)

const opts = {
  responseType: 'arraybuffer',
  headers: { 'Content-Type': 'application/octet-stream' }
}

console.log("Sending buffer: ", helloRequest.serializeBinary())

axios.post("http://localhost:8080/hello", helloRequest.serializeBinary(), opts)
  .then(resp => {
    const arr = new Uint8Array(resp.data)
    const helloResponse = proto.hello.HelloResponse.deserializeBinary(arr)
    console.log("Full name: ", helloResponse.getFullName())

    // Normally there is no need to JSON.stringify() as data is available for usage with `getXX` method
    // This is for the sake of printing.
    console.log("Metadata: ", JSON.stringify(helloResponse.getMetadata().toObject()))
  })
  .catch(console.error)