# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "google-protobuf", "~>3.15.6"
gem "httparty"

group :development do
  gem 'pry'
end