# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("hello.proto", :syntax => :proto3) do
    add_message "hello.Metadata" do
      optional :f_name_letter_count, :int32, 1
      optional :l_name_letter_count, :int32, 2
      optional :created_at, :message, 3, "google.protobuf.Timestamp"
    end
    add_message "hello.HelloRequest" do
      optional :first_name, :string, 1
      optional :last_name, :string, 2
      optional :metadata, :message, 3, "hello.Metadata"
    end
    add_message "hello.HelloResponse" do
      optional :full_name, :string, 1
      optional :metadata, :message, 2, "hello.Metadata"
    end
  end
end

module Hello
  Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.Metadata").msgclass
  HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.HelloRequest").msgclass
  HelloResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.HelloResponse").msgclass
end
